name: pysnowpark
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - nodefaults
dependencies:
  - python=3.8.15
  - snowflake-snowpark-python
  - cryptography==39.0.1=py38h9ce1e76_0
  - pyopenssl==23.0.0=py38h06a4308_0
  - pip
  - pip:
   # Snowflake
    - snowflake-cli-labs
    - streamlit
    - matplotlib
    - seaborn
